{{- if not .Values.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
stringData:
  FRONTEGG_CLIENT_ID: {{ required ".Values.frontegg.clientId is required" .Values.frontegg.clientId | quote }}
  FRONTEGG_CLIENT_SECRET: {{ required ".Values.frontegg.clientSecret is required" .Values.frontegg.clientSecret | quote }}
  SPICEDB_GRPC_PRESHARED_KEY: {{ required ".Values.spicedb.presharedKey is required" .Values.spicedb.presharedKey | quote }}
{{- end }}

