{{- $top := . -}}
{{- $values := $top.Values -}}
{{- if $values.e10sEngineSync.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "e10sEngineSync.name" $top }}
  labels:
    {{- include "e10sEngineSync.labels" $top | nindent 4 }}
spec:
  replicas: {{ $values.e10sEngineSync.replicaCount }}
  revisionHistoryLimit: {{ $values.revisionHistoryLimit | default 2 }}
  selector:
    matchLabels:
      {{- include "e10sEngineSync.selector.labels" $top | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "e10sEngineSync.labels" $top | nindent 8 }}
      annotations:
        {{- if $values.e10sEngineSync.secret.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/e10s-engine-sync/secret.yaml") $top | sha256sum }}
        {{- end }}
        checksum/configmap: {{ include (print $.Template.BasePath "/e10s-engine-sync/configmap.yaml") $top | sha256sum }}
        {{- with $values.e10sEngineSync.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if $values.serviceAccount.enabled }}
      serviceAccountName: {{ include "service.account.name" $top }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $values.e10sEngineSync.terminationGracePeriodSeconds | default 30 }}
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $values.e10sEngineSync.additionalVolumes }}
      volumes:
        {{- with $values.e10sEngineSync.additionalVolumes }}
        {{- tpl . $top | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ $values.e10sEngineSync.containerName | default "engine-sync" }}
          image: "{{ $values.e10sEngineSync.image.repository }}:{{ $values.e10sEngineSync.image.tag | default "latest" }}"
          imagePullPolicy: {{ $values.e10sEngineSync.image.pullPolicy | default "Always" }}
          env:
            # Frontegg credentials from secret
            - name: FRONTEGG_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "e10sEngineSync.secret.name" $top }}
                  key: FRONTEGG_CLIENT_ID
            - name: FRONTEGG_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "e10sEngineSync.secret.name" $top }}
                  key: FRONTEGG_CLIENT_SECRET
            # SpiceDB credentials from secret
            - name: SPICEDB_GRPC_PRESHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "e10sEngineSync.secret.name" $top }}
                  key: SPICEDB_GRPC_PRESHARED_KEY
            {{- with $values.e10sEngineSync.vars }}
            {{- tpl (toYaml .) $top | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "e10sEngineSync.configmap.name" $top }}
          {{- with $values.e10sEngineSync.additionalVolumeMounts }}
          volumeMounts:
            {{- tpl . $top | nindent 12 }}
          {{- end }}
          ports:
            {{- toYaml $values.e10sEngineSync.ports | nindent 12 }}
          {{- if $values.e10sEngineSync.livenessProbe }}
          {{- with $values.e10sEngineSync.livenessProbe }}
          {{- if . }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if $values.e10sEngineSync.readinessProbe }}
          {{- with $values.e10sEngineSync.readinessProbe }}
          {{- if . }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- end }}
          resources:
            {{- required ".Values.e10sEngineSync.resources is required" $values.e10sEngineSync.resources | toYaml | nindent 12 }}
      {{- with $values.e10sEngineSync.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $values.e10sEngineSync.affinity }}
      affinity:
        {{- tpl ($values.e10sEngineSync.affinity | toYaml) $top | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.frontegg.com/name
                      operator: In
                      values:
                        - {{ include "e10sEngineSync.name" $top }}
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- with $values.e10sEngineSync.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

